[build]
builder = "nixpacks"

[nixpacks]
pkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "python310Packages.wheel"]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"

[[deploy.healthcheck]]
path = "/"
interval = "15s"
timeout = "5s"
retries = 3

[phases.setup]
cmds = ["python -m venv /opt/venv", "source /opt/venv/bin/activate"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]